### ISSUE TITLE
Fails to build on Debian GNU/Hurd and GNU/kFreeBSD

### ISSUE THREAD

**Issue by jrtc27** [mate-desktop/libmatemixer#4]
This currently will not build on Debian GNU/Hurd with ALSA support:

```
alsa-constants.c:231:6: error: 'SND_MIXER_SCHN_SIDE_LEFT' undeclared here (not in a function)
     [SND_MIXER_SCHN_SIDE_LEFT]              = MATE_MIXER_CHANNEL_SIDE_LEFT,
      ^
alsa-constants.c:231:6: error: array index in initializer not of integer type
alsa-constants.c:231:6: note: (near initialization for 'alsa_channel_map_from')
alsa-constants.c:232:6: error: 'SND_MIXER_SCHN_SIDE_RIGHT' undeclared here (not in a function)
     [SND_MIXER_SCHN_SIDE_RIGHT]             = MATE_MIXER_CHANNEL_SIDE_RIGHT,
      ^
alsa-constants.c:232:6: error: array index in initializer not of integer type
alsa-constants.c:232:6: note: (near initialization for 'alsa_channel_map_from')
alsa-constants.c:233:6: error: 'SND_MIXER_SCHN_REAR_CENTER' undeclared here (not in a function)
     [SND_MIXER_SCHN_REAR_CENTER]            = MATE_MIXER_CHANNEL_BACK_CENTER
      ^
alsa-constants.c:233:6: error: array index in initializer not of integer type
alsa-constants.c:233:6: note: (near initialization for 'alsa_channel_map_from')
```

This is because ALSA is provided by liboss4-salsa on non-Linux Debian ports, which does not support side nor rear-centre channels (added by ALSA in http://git.alsa-project.org/?p=alsa-lib.git;a=commitdiff;h=597b4d0942f0618a3b5747f4b623474f57d13b82). Is this something that should be worked around in libmatemixer, or should liboss4-salsa be unsupported until side and rear-centre channel support is added to liboss4-salsa?

**Comment by jrtc27** [comment]
This also affects the kFreeBSD ports.

**Comment by jrtc27** [comment]
Perhaps this is better suited to the pkg-mate-team mailing list, but is there any chance of back-porting the fix to the Debian package, please?

**Comment by flexiondotorg** [comment]
I'll see what we can do in pkg-mate :-)
