### ISSUE TITLE
Build error with 1.21.0 release from po file

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/libmatemixer#7]
#### Expected behaviour
Finished build

#### Actual behaviour
make[2]: *** No rule to make target 'zu.po', needed by 'zu.gmo'.  Stop.

#### Steps to reproduce the behaviour
clone or download limbatemixer 1.21.0
./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu  --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode  --disable-schemas-compile  (my standard buiild option set for may packages, no problems before)
make -j

#### MATE general version
1.21

#### Package version
did not build

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None, I have all my MATE packages locally built

**Comment by raveit65** [comment]
I uploaded the missing po file https://github.com/mate-desktop/libmatemixer/commit/ae503695a8ca9902b8f52ccdf9828b640261f6a3
The file was only missing in public git repo , not in released tarball.
http://pub.mate-desktop.org/releases/1.21/libmatemixer-1.21.0.tar.xz
So changing the **tag** to latest commit should be sufficient.
Tag points to *ae50369* now.
https://github.com/mate-desktop/libmatemixer/releases

**Comment by lukefromdc** [comment]
OK, I just confirmed this to work, build from git master (my usual and matching this point at the moment) works fine. Closing, thanks for the fix.
